stages:
  - install

#---------------------------------------------------------------------------------------------------
# BACK: INSTALL
#---------------------------------------------------------------------------------------------------
install_back:
  stage: install
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
      when: always
    - if: $CI_COMMIT_BRANCH != "release"
      when: manual
  tags:
    - nodejs-20
  cache:
    - key:
        files: [ ./package-lock.json ]
      paths:   [ ./node_modules/ ]
  variables:
    NODE_ENV: production
  script:
    - npm i