# --------------------------------------------------------------------------------------------------
# Notes:
# - jobs are executed in the order indicated at root "stages" property
# - "needs" property needs an array of job names (not stages names)
# - linter needs install:dev as eslint and prettier are dev dependencies
# --------------------------------------------------------------------------------------------------

stages:
  - install
  - quality
  - tests
  - build

#---------------------------------------------------------------------------------------------------
# INSTALL
#---------------------------------------------------------------------------------------------------
install:
  stage: install
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_PIPELINE_SOURCE != "push"'
      when: manual
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: push
  tags:
    - nodejs-20
  variables:
    NODE_ENV: development
  script:
    - npm i

#---------------------------------------------------------------------------------------------------
# QUALITY (LINTER)
#---------------------------------------------------------------------------------------------------
quality:
  stage: quality
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE != "push"'
      when: manual
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull
  tags:
    - nodejs-20
  variables:
    NODE_ENV: development
  script:
    - npm run lint

#---------------------------------------------------------------------------------------------------
# TESTS
#---------------------------------------------------------------------------------------------------
tests:
  stage: tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE != "push"'
      when: manual
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull
  tags:
    - nodejs-20
  variables:
    NODE_ENV: development
  script:
    - npm run test

#---------------------------------------------------------------------------------------------------
# INSTALL
#---------------------------------------------------------------------------------------------------
build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
      when: on_success
    - if: $CI_COMMIT_BRANCH != "release"
      when: manual
  tags:
    - nodejs-20
  variables:
    NODE_ENV: production
  script:
    - npm i
