; local config file for RUDI API module

[server]
listening_address = 127.0.0.1
listening_port = 3000

[database]
db_url = mongodb://127.0.0.1/
db_name = rudi_prod

[logging]
should_log_in_file = true
should_show_error_pile = true
app_name = rudiprod.api
log_dir = ./logs
; name of the log file, no path: the file will be created in previous 'log_dir' folder
log_file = rudiprod-api.log
expires = 1d
log_level = debug

[syslog]
should_syslog = false
syslog_host = localhost
syslog_port = 514
syslog_facility = local4
syslog_protocol = unix
; Available values: bsd | 3164 | RFC3164 | 5424 | RFC5424
syslog_type = RFC5424
; full path for the place to send syslog messages
; unix: /dev/log
; macOS: /var/run/syslog
syslog_path = /var/run/syslog
; full path for the file that backups the syslog messages
syslog_file = /tmp/devLogs/rudi/syslog
syslog_node_name = dev

[portal]
;--- Portal metadata URL
portal_url = http://rudi.qualif.open-groupe.com
;  - URL suffix to push metadata
put_url = kalim/v1/resources
;  - URL suffix to get metadata
get_url = konsult/v1/datasets/{{id}}/metadatas

;--- Portal authentification URL
auth_url = http://rudi.qualif.open-groupe.com
;  - URL suffix to get a new token
auth_get = oauth/token
;  - URL suffix to check a token
auth_chk = oauth/check_token
;  - URL suffix to get the Portal public key
auth_pub = oauth/token_key

; credentials for the Producer Node on Portal side
login  = <mon_login>
passw  = <mon_mdp>

; the path to the Portal public key
path_portal_pub = ./0-ssh/portal.pub

; if false, requests frop the public 'api/v1' URL will not
; be controlled
should_control_public_requests = true

[security]
; if false, JWT from the headers of incoming requests (e.g. from 
; the producer node manager) will not be controlled
should_control_private_requests = true 

; file for the security configuration (key location + authorized
; route names for every authorized client)
profiles = ./0-ini/profiles.ini
