; Each profile their own section

; The routes names can be found in the file
; ../routes/routes.js 
; (look for "Route names")
;    pub_get_all_metadata
;    pub_get_one_metadata
;    pub_upsert_one_report
;    pub_get_all_obj_report
;    pub_get_one_obj_report
;    
;    prv_add_one
;    prv_upsert_one
;    prv_get_all
;    prv_get_one
;    prv_del_one
;    prv_del_many
;    prv_del_list
;    prv_get_orphans
;    prv_add_obj_report
;    prv_upsert_obj_report
;    prv_get_obj_report_list
;    prv_get_one_obj_report
;    prv_get_all_obj_report
;    prv_del_obj_report
;    prv_del_all_obj_report
;    prv_del_list_obj_report
;    
;    dev_get_every_thesaurus
;    dev_get_single_thesaurus
;    dev_get_all_licences
;    dev_get_all_licence_codes
;    dev_generate_uuid
;    dev_exposed_get_portal_token
;    dev_check_stored_token
;    dev_get_portal_metadata
;    dev_send_metadata_to_portal
;    dev_del_portal_metadata
;    dev_get_git_hash
;    dev_get_app_hash
;    dev_get_node_version
;    dev_get_logs
;    dev_get_last_log_lines
;    dev_get_collections


;--------------------------------------------------------------------------
; RUDI producer node - manager module
;--------------------------------------------------------------------------
[rudi_prod_manager]
pub_key=./0-ssh/rudi_prod_manager.pub

routes[]="prv_add_one"
routes[]="prv_upsert_one"
routes[]="prv_get_all"
routes[]="prv_get_one"
routes[]="prv_del_one"
routes[]="prv_get_orphans"
routes[]="prv_get_obj_report_list"
routes[]="prv_get_one_obj_report"
routes[]="prv_get_all_obj_report"

routes[]="dev_get_every_thesaurus"
routes[]="dev_get_single_thesaurus"
routes[]="dev_get_all_licences"
routes[]="dev_get_all_licence_codes"
routes[]="dev_generate_uuid"
routes[]="dev_get_logs"

;--------------------------------------------------------------------------
; RUDI producer node - API client module
;--------------------------------------------------------------------------
[rudi_api_client]
pub_key=./0-ssh/rudi_api_client.pub

routes[]="prv_add_one"
routes[]="prv_upsert_one"
routes[]="prv_get_all"
routes[]="prv_get_one"
routes[]="prv_del_one"
routes[]="prv_del_many"
routes[]="prv_del_list"
routes[]="prv_get_orphans"
routes[]="prv_add_obj_report"
routes[]="prv_upsert_obj_report"
routes[]="prv_get_obj_report_list"
routes[]="prv_get_one_obj_report"
routes[]="prv_get_all_obj_report"
routes[]="prv_del_obj_report"
routes[]="prv_del_all_obj_report"
routes[]="prv_del_list_obj_report"

routes[]="dev_get_every_thesaurus"
routes[]="dev_get_single_thesaurus"
routes[]="dev_get_all_licences"
routes[]="dev_get_all_licence_codes"
routes[]="dev_exposed_get_portal_token"
routes[]="dev_check_stored_token"
routes[]="dev_get_portal_metadata"
routes[]="dev_send_metadata_to_portal"
routes[]="dev_del_portal_metadata"
routes[]="dev_get_git_hash"
routes[]="dev_get_app_hash"
routes[]="dev_get_node_version"
routes[]="dev_get_logs"
routes[]="dev_get_last_log_lines"
routes[]="dev_get_collections"
routes[]="dev_drop_db"

;--------------------------------------------------------------------------
; RUDI producer node - Postman test client
;--------------------------------------------------------------------------
[rudi_api_pm]
pub_key=./0-ssh/rudi_api_pm.pub

routes[]="all"
