; local config file for RUDI API module

[server]
listening_address = 127.0.0.1
listening_port = 3000

[database]
db_url = mongodb://127.0.0.1/
db_name = rudi_prod

[logging]
app_name = rudiProxi
log_dir = ./logs
log_file = rudiProxi.log
