; local config file for RUDI API module

[server]
listening_address = 127.0.0.1
listening_port = 3000

[database]
db_url = mongodb://127.0.0.1/
db_name = rudi_prod

[logging]
app_name = rudiProxy
log_dir = ./logs
log_file = rudiProxy.log
expires = 1d
log_level = debug

[portal]
auth_url = https://rudi.qualif.open-groupe.com/auth
auth_get = get_token
auth_chk = check_token

login  = 4c9ee0f14e835927a1bbafde0eb89fb3
passw  = 60ba-3ae52f3c31!58aa432208123
secret = d1518973-53af-4852-a5b0-20cd0f8e2a81
publicKey = ./pub/portal.pub
publicKeyUrl = https://rudi.qualif.open-groupe.com/oauth/token_key

put_url = https://rudi.qualif.open-groupe.com/resources
get_url = https://rudi.qualif.open-groupe.com/datasets/{{id}}/metadatas

; if false, requests frop the public 'api/v1' URL will not
; be controlled
should_control_public_requests = false

[security]
; if false, JWT from the headers of incoming requests (e.g. from 
; the producer node manager) will not be controlled
should_control_private_requests = false

; file for the security configuration (key location + authorized
; route names for every authorized client)
profiles = ./0-ini/profiles.ini
