; local config file for RUDI API module

[server]
listening_address = 127.0.0.1
listening_port = 3000

[database]
db_url = mongodb://127.0.0.1/
db_name = rudi_prod

[logging]
app_name = rudiProxi
log_dir = ./logs
log_file = rudiProxi.log
expires = 1d

[portal]
auth_url = http://127.0.0.1/auth
auth_get = get_token
auth_chk = check_token

login  = 4c9ee0f14e835927a1bbafde0eb89fb3
passw  = 60ba-3ae52f3c31!58aa432208123
secret = d1518973-53af-4852-a5b0-20cd0f8e2a81

put_url = http://127.0.0.1//resources
get_url = http://127.0.0.1/datasets/{{id}}/metadatas
